# Generated by Django 4.1.7 on 2023-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigos', models.CharField(max_length=50)),
            ],
        ),
    ]
