# Generated by Django 4.1.7 on 2023-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_amigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
            ],
        ),
    ]
